version: '3.7'

services:
  api_db:
    image: postgres
    container_name: api_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=api_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: apilogin
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - api_db
    depends_on:
      - api_db

volumes:
  pgdata:
    driver: local