version: '3.7'

services:
  apilogin_db:
    image: postgres
    container_name: apilogin_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=apilogin_db
    volumes:
      - pgdata:/data/postgres
  api_app:
    build: .
    container_name: apilogin
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - apilogin_db
    depends_on:
      - apilogin_db

volumes:
  pgdata:
    driver: local